### PR TITLE
[FIX] emc_taxshelter_report: 't' in mail template

### PR DESCRIPTION
**Pull request by remytms**
This fix weird 't' appearing in the translation of emails. There was a
mix of space and tab indentation in xml files. Tabulation indentation
generate \t code in fr_BE.po.

So this commit removes the tabulation indetation for xml file and fix
the translation in i18n/fr_BE.po.

How to test :

* From a fresh DB.
* Install the easy_my_coop_taxshelter_report plugin.
* Load the French (BE) translation.
* For Tax Shelter mail template, the translation is clean (no 't' at the begining of some lines)

### CODE REVIEW

**Review by houssine78 — CHANGES_REQUESTED** [review]
need rebase

**Comment by robinkeunen** [comment]
Oulah, ya dla vieille PR qui traine!

**Comment by vdewulf** [comment]
@remytms Could you finish this task, please?
thanks.

**Comment by remytms** [comment]
@houssine78 , rebase done.

**Comment by houssine78** [comment]
@remytms thanks!

**Pull request merged**
