### PR TITLE
[IMP] easy_my_coop_taxhelter_report

### PR DESCRIPTION
**Pull request by vdewulf**
Updated xml reports and css in order to have one page certificate.
Made the same design for the signature on both report
In CSS file: Changed the font size to make it smaller in px in place of pt
Changed the size of the image for the signature to make it smaller

### CODE REVIEW

**Comment by houssine78** [comment]
:+1:

**Comment by remytms** [comment]
@vdewulf , I tested it on my local computer. The render is ok, but still on 2 pages. Do you tested it on another environment ?

**Comment by remytms** [comment]
@vdewulf, ok it's an issue of my configuration of wkhtmltopdf.

**Review by remytms — APPROVED** [review]
Good job. We could have left `pt` as unit for the font-size as it is intended for printing. But `px` is ok.

**Comment by vdewulf** [comment]
Thanks for the testing.
@remytms Could you put this branch and test for another customer just to make sure it's okay?

**Comment by remytms** [comment]
@vdewulf, @houssine78 , it's tested on gestion-test.bees-coop.be. Everything is fine. Very good work. :)

**Pull request merged**
