### PR TITLE
[FIX] easy_my_coop: 't' in mail template

### PR DESCRIPTION
**Pull request by remytms**
This fix weird 't' appearing in the translation of emails. There was a
mix of space and tab indentation in xml files. Tabulation indentation
generate \t code in fr_BE.po.

So this commit removes the tabulation indetation for xml file and fix
the translation in i18n/fr_BE.po.

### CODE REVIEW

**Comment by remytms** [comment]
How to test :

* From a fresh DB.
* Install the easy_my_coop_taxshelter_report plugin.
* Load the French (BE) translation.
* For Tax Shelter mail template, the translation is clean (no 't' at the begining of some lines)

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
need a rebase of your PR?

**Comment by houssine78** [comment]
Could you do a rebase?

**Comment by houssine78** [comment]
@remytms

**Comment by remytms** [comment]
@houssine78 , rebase done. :)

**Review by houssine78 — APPROVED** [review]

**Pull request merged**
